#by zaz, it's not very good, but what did you expect, rainbowdash is way better
#2013

.name		"fluttershyfluttershyfluttershyfluttershyfluttershyfluttershyfluttershyfluttershyfluttershy"
.comment	"oh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet t a scary projet a scary projet sssct"

ld %42, r3
st r3, 60
st r3, r4
aff r4
