#by zaz, it's not very good, but what did you expect, rainbowdash is way better
#2013

.name		"fluttershyfluttershyfluttershyfluttershyfluttershyfluttershyfluttershyfluttershyfluttershy"
.comment	"oh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projectoh, my, what a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet a scary projet t a scary projet a scary projet sssct"

start:
	ld 4, r2
	zjmp %0
